services:
  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kadumorais
      POSTGRES_DB: banco_estoque
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - kadu-network

networks:
  kadu-network:
    driver: bridge

volumes:
  db_data:
